### ISSUE TITLE
Accessing landing page

### ISSUE THREAD

**Issue by AlexanderYW** [zakodium/adonis-apollo#46]
I see that the latest release contains apollo landing page

But when i visit /graphql in my application i get this error
```json
{
  "errors": [
    {
      "message": "This operation has been blocked as a potential Cross-Site Request Forgery (CSRF). Please either specify a 'content-type' header (with a type that is not one of application/x-www-form-urlencoded, multipart/form-data, text/plain) or provide a non-empty value for one of the following headers: x-apollo-operation-name, apollo-require-preflight\n",
      "extensions": {
        "code": "BAD_REQUEST",
        "stacktrace": [
          "BadRequestError: This operation has been blocked as a potential Cross-Site Request Forgery (CSRF). Please either specify a 'content-type' header (with a type that is not one of application/x-www-form-urlencoded, multipart/form-data, text/plain) or provide a non-empty value for one of the following headers: x-apollo-operation-name, apollo-require-preflight",
          "",
          "    at new GraphQLErrorWithCode (/backend/node_modules/@apollo/server/src/internalErrorClasses.ts:15:5)",
          "    at new BadRequestError (/backend/node_modules/@apollo/server/src/internalErrorClasses.ts:116:5)",
          "    at preventCsrf (/backend/node_modules/@apollo/server/src/preventCsrf.ts:91:9)",
          "    at ApolloServer.executeHTTPGraphQLRequest (/backend/node_modules/@apollo/server/src/ApolloServer.ts:1024:20)",
          "    at processTicksAndRejections (node:internal/process/task_queues:95:5)",
          "    at graphqlAdonis (/backend/node_modules/adonis-apollo/src/graphqlAdonis.ts:20:5)"
        ]
      }
    }
  ]
}
```

Disabling CSRF does not solve it. Am i missing something, or am i just to early for this feature? :)

**Comment by targos** [comment]
Have you checked https://github.com/zakodium/adonis-apollo#badrequesterror-this-operation-has-been-blocked-as-a-potential-cross-site-request-forgery-csrf ?

**Comment by AlexanderYW** [comment]
That actually solved it!, I totally missed that part :D
